<?php
define ( 'CORE_ROOT', '/home/mme/core/' );
define ( 'DATABASE_HOST', 'localhost' );
define ( 'DATABASE_NAME', '' );
define ( 'DATABASE_USER', '' );
define ( 'DATABASE_PASSWORD', '' );
define ( 'PRODUCTION', false );
define ( 'DEFAULT_PAGE', 'oai' );
define ( 'SITE_NAME', 'Museum Metadata Exchange' );
define ( 'SITE_DESCRIPTION', '' );
define ( 'SITE_ORGANISATION', '' );
define ( 'EMAIL_WEBMASTER_ADDRESS', 'email@example.com' );
define ( 'EMAIL_WEBMASTER_NAME', 'Webmaster' );
define ( 'EMAIL_WEBMASTER', 'Webmaster <email@example.com>' );
define ( 'SITE_URL_DISPLAY', 'example.com' );
?>